apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-wave2
  namespace: wave2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.27
